export const menuData = [
    {
      "checked": false,
      "code": "GZT",
      "createTime": null,
      "createUser": null,
      "enable": true,
      "icon": null,
      "id": "211101082631941008",
      "name": "工作台",
      "pageCache": null,
      "parentId": null,
      "serialNum": 1,
      "type": 1,
      "updateTime": "2021-11-01 20:26:36",
      "updateUser": "60468483",
      "url": "/platform",
      "busSys": null,
      "bspCode": "BIMDC_GONGZUOTA",
      "extMenuId": null,
      "extMenuParentId": null,
      "btpMenuId": null,
      "btpParentMenuId": null,
      "bspSort": 1,
      "activeIcon": null,
      "children": null,
      "functionVOs": null,
      "menuDependencies": null,
      "nodeType": null
    },
    {
      "checked": false,
      "code": null,
      "createTime": null,
      "createUser": null,
      "enable": true,
      "icon": null,
      "id": "130985271259958224",
      "name": "项目",
      "pageCache": null,
      "parentId": null,
      "serialNum": 2,
      "type": 1,
      "updateTime": "2021-03-17 13:49:19",
      "updateUser": "11acb2c1589e40a0b0c638f1859fcaf3",
      "url": "/project",
      "busSys": null,
      "bspCode": "BIMDC_XIANGM",
      "extMenuId": null,
      "extMenuParentId": null,
      "btpMenuId": null,
      "btpParentMenuId": null,
      "bspSort": 2,
      "activeIcon": null,
      "children": [
        {
          "checked": false,
          "code": "XMXQ",
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "220104110330191004",
          "name": "项目详情",
          "pageCache": null,
          "parentId": "130985271259958224",
          "serialNum": 1,
          "type": 1,
          "updateTime": "2022-01-04 23:05:37",
          "updateUser": "60470536",
          "url": "/project/overview",
          "busSys": null,
          "bspCode": "BIMDC_XIANGM_XMXQ",
          "extMenuId": null,
          "extMenuParentId": null,
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 1,
          "activeIcon": null,
          "children": null,
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        },
        {
          "checked": false,
          "code": "2",
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "211021090957738006",
          "name": "成员管理",
          "pageCache": null,
          "parentId": "130985271259958224",
          "serialNum": 3,
          "type": 1,
          "updateTime": "2021-10-21 21:10:01",
          "updateUser": "60470536",
          "url": "/project/memberManage",
          "busSys": null,
          "bspCode": "BIMDC_XIANGM_CYGL",
          "extMenuId": null,
          "extMenuParentId": null,
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 3,
          "activeIcon": null,
          "children": null,
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        },
        {
          "checked": false,
          "code": "WDGL",
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "1309377175866179584",
          "name": "文档管理",
          "pageCache": null,
          "parentId": "130985271259958224",
          "serialNum": 4,
          "type": 1,
          "updateTime": "2021-10-21 21:15:26",
          "updateUser": "60470536",
          "url": "/project/documentManagement",
          "busSys": null,
          "bspCode": "WDGL",
          "extMenuId": "1309377175866179584",
          "extMenuParentId": "0",
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 4,
          "activeIcon": null,
          "children": null,
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        },
        {
          "checked": false,
          "code": "4",
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "211021091049226009",
          "name": "BIM集成",
          "pageCache": null,
          "parentId": "130985271259958224",
          "serialNum": 5,
          "type": 1,
          "updateTime": "2021-10-21 21:10:53",
          "updateUser": "60470536",
          "url": "/project/newModelMap",
          "busSys": null,
          "bspCode": "BIMDC_XIANGM_BJC",
          "extMenuId": null,
          "extMenuParentId": null,
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 5,
          "activeIcon": null,
          "children": null,
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        },
        {
          "checked": false,
          "code": "6",
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "211115073246403006",
          "name": "图纸归档/申请",
          "pageCache": null,
          "parentId": "130985271259958224",
          "serialNum": 6,
          "type": 1,
          "updateTime": "2021-11-15 19:43:56",
          "updateUser": "60367545",
          "url": "/project/drawing",
          "busSys": null,
          "bspCode": "BIMDC_XIANGM_TZGD/SQ",
          "extMenuId": null,
          "extMenuParentId": null,
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 6,
          "activeIcon": null,
          "children": null,
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        },
        {
          "checked": false,
          "code": "SJSC",
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "211223113100421002",
          "name": "数据生产",
          "pageCache": null,
          "parentId": "130985271259958224",
          "serialNum": 7,
          "type": 1,
          "updateTime": "2021-12-23 23:33:44",
          "updateUser": "60470536",
          "url": "/project/dataProd",
          "busSys": null,
          "bspCode": "BIMDC_XIANGM_SJSC",
          "extMenuId": null,
          "extMenuParentId": null,
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 7,
          "activeIcon": null,
          "children": [
            {
              "checked": false,
              "code": "SJSCXQ",
              "createTime": null,
              "createUser": null,
              "enable": true,
              "icon": null,
              "id": "211224103416285004",
              "name": "数据生产详情",
              "pageCache": null,
              "parentId": "211223113100421002",
              "serialNum": 1,
              "type": 3,
              "updateTime": "2021-12-24 10:34:18",
              "updateUser": "60468483",
              "url": "/project/dataProd/processInfo",
              "busSys": null,
              "bspCode": "BIMDC_XIANGM_SJSC_SJSCXQ",
              "extMenuId": null,
              "extMenuParentId": null,
              "btpMenuId": null,
              "btpParentMenuId": null,
              "bspSort": 1,
              "activeIcon": null,
              "children": null,
              "functionVOs": null,
              "menuDependencies": null,
              "nodeType": null
            }
          ],
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        }
      ],
      "functionVOs": null,
      "menuDependencies": null,
      "nodeType": null
    },
    {
      "checked": false,
      "code": "/document",
      "createTime": null,
      "createUser": null,
      "enable": true,
      "icon": null,
      "id": "1230977562131334641",
      "name": "我的",
      "pageCache": null,
      "parentId": null,
      "serialNum": 3,
      "type": 1,
      "updateTime": "2021-03-17 13:49:35",
      "updateUser": "11acb2c1589e40a0b0c638f1859fcaf3",
      "url": "/document",
      "busSys": null,
      "bspCode": "BIMDC_WOD",
      "extMenuId": null,
      "extMenuParentId": null,
      "btpMenuId": null,
      "btpParentMenuId": null,
      "bspSort": 3,
      "activeIcon": null,
      "children": [
        {
          "checked": false,
          "code": "1",
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "211021091150603003",
          "name": "我的任务",
          "pageCache": null,
          "parentId": "1230977562131334641",
          "serialNum": 1,
          "type": 1,
          "updateTime": "2021-10-21 21:11:53",
          "updateUser": "60470536",
          "url": "/document/task",
          "busSys": null,
          "bspCode": "BIMDC_WOD_WDRW",
          "extMenuId": null,
          "extMenuParentId": null,
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 1,
          "activeIcon": null,
          "children": null,
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        },
        {
          "checked": false,
          "code": "/project/delivery",
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "1309377175446179584",
          "name": "我的收发",
          "pageCache": null,
          "parentId": "1230977562131334641",
          "serialNum": 2,
          "type": 1,
          "updateTime": "2021-10-21 21:12:21",
          "updateUser": "60470536",
          "url": "/document/documentDelivery",
          "busSys": null,
          "bspCode": "BIMDC_WOD_WDXF",
          "extMenuId": null,
          "extMenuParentId": null,
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 2,
          "activeIcon": null,
          "children": null,
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        },
        {
          "checked": false,
          "code": "/project/fileShare",
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "12430977563131855",
          "name": "我的分享",
          "pageCache": null,
          "parentId": "1230977562131334641",
          "serialNum": 3,
          "type": 1,
          "updateTime": "2021-10-21 21:12:31",
          "updateUser": "60470536",
          "url": "/document/fileShare",
          "busSys": null,
          "bspCode": "BIMDC_WOD_WDFX",
          "extMenuId": null,
          "extMenuParentId": null,
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 3,
          "activeIcon": null,
          "children": null,
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        },
        {
          "checked": false,
          "code": null,
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "12430977563131860",
          "name": "我的收藏",
          "pageCache": null,
          "parentId": "1230977562131334641",
          "serialNum": 4,
          "type": 1,
          "updateTime": "2021-08-18 09:40:23",
          "updateUser": "60534672",
          "url": "/document/favorite",
          "busSys": null,
          "bspCode": "BIMDC_WOD_WDSZ",
          "extMenuId": null,
          "extMenuParentId": null,
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 4,
          "activeIcon": null,
          "children": null,
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        },
        {
          "checked": false,
          "code": "7",
          "createTime": null,
          "createUser": null,
          "enable": true,
          "icon": null,
          "id": "211115073153334003",
          "name": "我的流程",
          "pageCache": null,
          "parentId": "1230977562131334641",
          "serialNum": 6,
          "type": 1,
          "updateTime": "2021-11-15 19:44:00",
          "updateUser": "60367545",
          "url": "/document/process",
          "busSys": null,
          "bspCode": "BIMDC_WOD_WDLC",
          "extMenuId": null,
          "extMenuParentId": null,
          "btpMenuId": null,
          "btpParentMenuId": null,
          "bspSort": 6,
          "activeIcon": null,
          "children": null,
          "functionVOs": null,
          "menuDependencies": null,
          "nodeType": null
        }
      ],
      "functionVOs": null,
      "menuDependencies": null,
      "nodeType": null
    }
  ]