export const menuData = [
  {
    checked: false,
    code: 'GZT',
    createTime: null,
    createUser: null,
    enable: true,
    icon: null,
    id: '211101082631941008',
    name: '工作台',
    pageCache: null,
    parentId: null,
    serialNum: 1,
    type: 1,
    updateTime: '2021-11-01 20:26:36',
    updateUser: '60468483',
    url: '/platform',
    busSys: null,
    bspCode: 'BIMDC_GONGZUOTA',
    extMenuId: null,
    extMenuParentId: null,
    btpMenuId: null,
    btpParentMenuId: null,
    bspSort: 1,
    activeIcon: null,
    children: null,
    functionVOs: null,
    menuDependencies: null,
    nodeType: null,
  },
  {
    checked: false,
    code: null,
    createTime: null,
    createUser: null,
    enable: true,
    icon: null,
    id: '130985271259958224',
    name: '项目',
    pageCache: null,
    parentId: null,
    serialNum: 2,
    type: 1,
    updateTime: '2021-03-17 13:49:19',
    updateUser: '11acb2c1589e40a0b0c638f1859fcaf3',
    url: '/project',
    busSys: null,
    bspCode: 'BIMDC_XIANGM',
    extMenuId: null,
    extMenuParentId: null,
    btpMenuId: null,
    btpParentMenuId: null,
    bspSort: 2,
    activeIcon: null,
    children: [
      {
        checked: false,
        code: 'XMXQ',
        createTime: null,
        createUser: null,
        enable: true,
        icon: null,
        id: '220104110330191004',
        name: '项目详情',
        pageCache: null,
        parentId: '130985271259958224',
        serialNum: 1,
        type: 1,
        updateTime: '2022-01-04 23:05:37',
        updateUser: '60470536',
        url: '/project/overview',
        busSys: null,
        bspCode: 'BIMDC_XIANGM_XMXQ',
        extMenuId: null,
        extMenuParentId: null,
        btpMenuId: null,
        btpParentMenuId: null,
        bspSort: 1,
        activeIcon: null,
        functionVOs: null,
        menuDependencies: null,
        nodeType: null,
        children: [
          {
            checked: false,
            code: 'XMXQ1',
            createTime: null,
            createUser: null,
            enable: false,
            icon: null,
            id: '220104110330191004',
            name: '项目详情1',
            pageCache: null,
            parentId: '130985271259958224',
            serialNum: 1,
            type: 1,
            updateTime: '2022-01-04 23:05:37',
            updateUser: '60470536',
            url: '/project/overview/overview1',
            busSys: null,
            bspCode: 'BIMDC_XIANGM_XMXQ1',
            extMenuId: null,
            extMenuParentId: null,
            btpMenuId: null,
            btpParentMenuId: null,
            bspSort: 1,
            activeIcon: null,
            functionVOs: null,
            menuDependencies: null,
            nodeType: null,
          },
        ],
      },
    ],
  },
];
